services:
  kytos:
    image: amlight/kytos:latest
    privileged: true
    volumes:
      - "./kytos-init.sh:/kytos-init.sh"
      - "./tests:/tests"
      - "./scripts/wait_for_mongo.py:/scripts/wait_for_mongo.py"
    command:
      - /kytos-init.sh
    environment:
      MONGO_USERNAME: napp_user
      MONGO_PASSWORD: napp_pw
      MONGO_DBNAME: napps
      MONGO_HOST_SEEDS: "mongo1t:27027,mongo2t:27028,mongo3t:27029"
      KAFKA_HOST_ADDR: "kytos-broker:19092"  
    depends_on:
      - mongo-setup
      - kytos-broker
  kytos-broker:
    image: apache/kafka:latest
    container_name: kytos-broker
    restart: unless-stopped
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:19092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kytos-broker:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kytos-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  mongo-setup:
    container_name: mongo-test-rs-init
    image: mongo:7.0
    restart: on-failure
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/scripts/rs-init.sh"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: root_pw
      MONGO_USERNAME: napp_user
      MONGO_PASSWORD: napp_pw
      MONGO_DBNAME: napps
      MONGO_NODES: mongo1t:27027 mongo2t:27028 mongo3t:27029
    depends_on:
      - mongo1t
      - mongo2t
      - mongo3t
  mongo1t:
    container_name: mongo1t
    image: mongo:7.0
    ports:
      - 27027:27027
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27027" ]
    depends_on:
      - mongo2t
      - mongo3t
  mongo2t:
    container_name: mongo2t
    image: mongo:7.0
    ports:
      - 27028:27028
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27028" ]
  mongo3t:
    container_name: mongo3t
    image: mongo:7.0
    ports:
      - 27029:27029
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27029" ]
#  mininet:
#      image: italovalcy/mininet:latest
#      privileged: true
#      links:
#        - "kytos"
#      command:
#        - /usr/bin/tail -f /dev/null
